import {controlGuide} from './control-guide.mjs';
import {loopVisual} from './loop-visual.mjs';
import {sessionHero} from './tape-session.mjs';
import {wordmark} from './brand-marks.mjs';
const photo=(name,alt)=>`<img src="/product/${name}.webp" width="1536" height="1024" loading="lazy" alt="${alt}">`;
const tag=t=>`<p class="tp-label">${t}</p>`;
const button=(t,url,extra='')=>`<a class="tp-button" href="${url}" ${extra}>${t}</a>`;
export function tapeProduct(){return `<section class="tp-hero" id="collection"><div class="tp-hero-heading">${tag('T—01 / THE SESSION DECK')}<h1>TOUCH.<br> PLAY.<br><em>REPEAT.</em></h1><p>A four-layer loop instrument.<br>And yes, you can play this one.</p><div class="tp-hero-actions">${button('Play the deck','#collection','data-start-deck')}<a class="tp-button tp-button-secondary" href="#experience">Show me how</a></div><p class="tp-audio-notice" data-audio-notice role="status" hidden></p><span class="tp-hero-status">BUILT-IN SOUNDS. OPTIONAL MIC RECORDING.<br>PRESS PLAY TO BEGIN. NOTHING UPLOADED.</span><span class="tp-edition">IVORY / COBALT<br>A WEB PROTOTYPE. A REAL-WORLD AMBITION.</span></div>${sessionHero()}</section>
<section class="tp-strip" aria-label="Design highlights"><span>TACTILE BY DESIGN</span><span>FOUR INDEPENDENT LAYERS</span><span>AN ARM FOR EXPRESSION</span><span>LESS SCREEN. MORE FEELING.</span></section>
<section class="tp-intro" id="story">${tag('01 / BACK IN TOUCH')}<h2>YOUR MUSIC.<br><em>WITH FEELING.</em></h2><div><p>A melody you hum. A rhythm on the table. A bass line that needs another pass. Catch one idea, then build around it.</p><p>T—01 puts four loops under your hands. A knob for each layer. A disc to slow, hold and scrub a sound. A silver expression arm to sweep its tone. Everything you touch has a reason to be there.</p><p>Pick from twelve original drum, bass, chord and texture loops, or record your own. The instrument above already works in your browser. The next ambition is to build a standalone physical deck with the same feel. Try it. Make something. Help shape what comes next.</p></div></section>
<section class="tp-blue" id="design"><header>${tag('AN OBJECT YOU LEAVE OUT.')}<h2>GOOD FROM<br><em>EVERY SIDE.</em></h2><span class="tp-stamp">TAPE<br>MORE FEELING<br>LESS DISTRACTION</span></header>${photo('session-blue-v8','TAPE Session Deck concept on a cobalt studio background, with four aligned layer knobs and a curved silver expression arm')}<div class="tp-blue-bottom"><span>IVORY METAL / GRAPHITE BASE</span><p>A low silhouette, a precise edge, a little room underneath.<br>Hardware with presence. Without taking over the room.</p></div></section>
${controlGuide()}
<section class="tp-materials" id="materials">${tag('03 / EVERYTHING HAS ITS PLACE')}<h2>THE DETAILS<br><em>DO THE TALKING.</em></h2><div class="tp-detail-grid"><article><span class="tp-number">01</span><h3>Metal, with a softer side.</h3><p>The material direction is a machined aluminum upper shell, a coated steel lower body and tactile PBT keys. Warm ivory. Dry texture. Real weight under your hands.</p><span>CHASSIS / BUILT TO STAY</span></article><article><span class="tp-number">02</span><h3>Put a hand on time.</h3><p>A proposed motorized disc turns with the session. Touch it to take over a layer’s playback. In this demo, release it to rejoin the running timeline. Your other loops keep moving.</p><span>DISC / TIME & MOVEMENT</span></article><article><span class="tp-number">03</span><h3>An arm with a new purpose.</h3><p>The silver arm controls tone. Sweep its red grip inward to darken the selected layer; move it out to bypass. It hovers above the disc. No stylus, no grooves, no precious records to scratch.</p><span>EXPRESSION ARM / TONE & TEXTURE</span></article></div></section>
<section class="tp-living" id="ritual">${photo('session-lifestyle-v8','TAPE product concept on a walnut music desk in warm afternoon light, with four silver layer dials and a speaker')}<div>${tag('MAKE A LITTLE SPACE.')}<h2>ONE MORE LAYER.<br>THEN WE’LL GO.</h2><p>A place for the idea.<br>A reason to stay with it.</p></div></section>
<section class="tp-connection" id="setup"><div>${tag('04 / ONE IDEA BECOMES ANOTHER')}<h2>YOUR SOUND.<br><em>YOUR WAY IN.</em></h2><p>Start with a rhythm. Hum something over it. Add a bass line, then a little texture. Each sound repeats on its own layer; together, they become your loop.</p><p>In the browser, choose built-in sounds on the main dial or record with your microphone. The physical direction adds dedicated inputs for a mic, guitar or stereo synth—so the same four-layer idea can grow with your setup.</p><a class="tp-text-link" href="#experience">Explore the controls</a></div>${loopVisual()}</section>
<section class="tp-specs" id="details"><header>${tag('05 / THE BUILD, IN THE OPEN')}<h2>KNOW<br><em>YOUR DECK.</em></h2><p>These are engineering targets for the physical instrument. The browser demo proves the interaction; it does not prove a motor, circuit board or manufacturing process.</p><p>We’re publishing the architecture, cost assumptions and tests that need to pass before taking a physical product to production.</p><a class="tp-text-link" href="https://github.com/ethanplusai/tape/blob/main/docs/hardware/research.md" target="_blank" rel="noopener noreferrer">Read the engineering & cost study</a></header><dl>${[
['Instrument','Four-layer digital looper · standalone hardware direction'],['Audio target','48 kHz / 24-bit conversion · 32-bit float internal processing · four stereo layers'],['Loop memory target','Up to five minutes per layer, with one undo level per layer; subject to prototype benchmarks'],['Performance disc','200 mm direction · motor-assisted rotation · touch takeover · magnetic position sensing'],['Controls','Four push-encoders · three transport keys · push-to-enter main dial · expression arm · output wheel'],['Connections target','Mic with switchable phantom power · Hi-Z instrument · stereo line input · balanced stereo out · headphones'],['Local storage target','16 GB eMMC system and project storage · USB backup'],['Materials direction','Machined aluminum upper shell · coated steel base · aluminum knobs · PBT keycaps'],['Size direction','310 × 245 × 62 mm enclosure · approximately 2–3 kg; arm clearance and final mass to validate'],['Power direction','External USB-C supply · no battery in the first version'],['Playable now','Four mono layers · mic recording · 12 library loops · overdub · undo / redo · local project and WAV saving'],['Still to prove','Low-noise motor and disc feel · audio latency · thermal performance · reliable controls · manufacturability']
].map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('')}</dl></section>
<section class="tp-faq" id="questions">${tag('BEFORE THE FIRST LOOP')}<h2>A FEW GOOD QUESTIONS.</h2>${[
['Can I buy T—01?','Not yet. This is a working web prototype and a proposed physical product, built by Ethan. Product imagery is generated concept imagery. There is no working physical prototype or active crowdfunding campaign yet, and we are not accepting orders or payments.'],
['What would it cost?','The working price direction is $1,999 before tax and shipping. It is a planning assumption, not an offer. The published cost model explores a 500-unit first run, development, testing and contingency. Supplier quotes and a validated prototype must come before a fixed price or funding goal.'],
['Is this a record player?','It is a digital looping instrument. The disc is a performance surface and the arm controls a filter. Neither reads audio from a vinyl record.'],
['How does the main dial work?','On the tempo screen, turn it to change BPM. Click once to open MAIN. Turn to highlight an option, then click to enter it. Turn to adjust a setting, then click to return. Hold the dial or press Escape to go back. SOUND chooses a library loop for the selected layer; LOOP sets recording options; INPUT sets mic gain; SESSION handles saving and loading.'],
['Can I play without recording anything?','Yes. ROOM 01 includes twelve original loops: drums, bass, chords and textures. Select a layer, press the main dial and enter SOUND. Choose a type, turn to a sound and press to load. During playback, changes join at the next bar. OFF empties only that layer. Mic recordings require confirmation before replacement; Undo restores the previous sound.'],
['Where do my recordings go?','Your mic audio is processed locally in this browser. It is never uploaded. SESSION → SAVE downloads an editable .tape file; EXPORT downloads a mixed WAV. SAVE includes your library sounds and recorded layers. Unsaved audio disappears when you reload or leave.'],
['Will the physical version work exactly like the demo?','The core workflow is the target, with stereo layers and physical inputs added. Disc feel, the arm’s clearance, quiet motor operation, latency and the internal electronics still need physical testing. A physical arm will need to pick up a saved filter value smoothly when you change layers; this demo can move it automatically.'],
['What happens next?','First, test the audio engine and the motorized disc with real hardware. Then build an engineering prototype, get independent manufacturing quotes and test demand at the intended price. A public funding campaign comes after those steps, with a working physical prototype and a costed production plan.']
].map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">＋</span></summary><p>${a}</p></details>`).join('')}</section>
<section class="tp-last" id="build-it">${tag('SOME IDEAS ARE WORTH REPEATING.')}<h2>LET’S MAKE<br>THE REAL ONE.</h2><p class="tp-launch-note">A playable idea today. A physical instrument worth building next.<br>Follow the prototypes, the decisions and the first production plan.</p><div class="tp-launch-panel"><article><b>$1,999</b><span>WORKING PRICE DIRECTION<br>BEFORE TAX & SHIPPING</span></article><article><b>500</b><span>UNITS IN THE PLANNING CASE<br>NO PRODUCTION COMMITMENT YET</span></article><article><b>01 / 04</b><span>WEB PROTOTYPE → HARDWARE<br>→ VALIDATION → PRODUCTION</span></article></div><p class="tp-funding-label">PRELAUNCH / NO ORDERS, DEPOSITS OR PAYMENTS</p><div>${button('Get build updates','https://ethanplus.ai/newsletter')}<a class="tp-text-link" href="https://github.com/ethanplusai/tape" target="_blank" rel="noopener noreferrer">Explore the open source demo</a></div><p class="tp-launch-note">Build updates are part of Ethan’s email newsletter.<br>For TAPE feedback, find <a href="https://x.com/ethanplusai">@ethanplusai on X</a>.</p></section>`;}
export function tapeFooter(){return `<footer class="tp-footer"><div class="tp-footer-top"><p>PRECISION HARDWARE.<br>VERY HUMAN HABITS.</p><nav aria-label="Tape product"><span>THE DECK</span><a href="#collection">Play the prototype</a><a href="#experience">Learn the controls</a><a href="#setup">Connections & setup</a></nav><nav aria-label="Tape resources"><span>THE BUILD</span><a href="#details">Engineering targets</a><a href="https://github.com/ethanplusai/tape/blob/main/docs/hardware/research.md">Research & cost model</a><a href="#questions">Questions & answers</a></nav><nav aria-label="Behind Tape"><span>BY ETHAN</span><a href="https://x.com/ethanplusai">Follow on X</a><a href="https://ethanplus.ai/newsletter">Get build updates</a><a href="https://github.com/ethanplusai/tape">Source on GitHub</a></nav></div><a class="tp-footer-logo" href="#main" aria-label="Tape, back to top">${wordmark()}</a><div class="tp-footer-bottom"><span>T—01 / IVORY—COBALT / SESSION DECK</span><span>WORKING WEB PROTOTYPE · GENERATED CONCEPT IMAGERY</span><a href="https://ethanplus.ai">Built by Ethan</a></div></footer>`;}
